import { POKEMON } from "./asset_keys";
import { Pokemon } from "./typedef";

export const POKEMON_DATA: { [key: string]: Pokemon } = {
  // Normal Type Pokemon
  RATTATA: {
    PokemonId: 21,
    name: "rattata",
    assetKey: POKEMON.RATTATA,
    assetFrame: 0,
    type: "NORMAL",
    baseAttack: 12,
    maxHp: 30,
    currentHp: 30,
    attackIds: [5, 11, 1, 3], // Tackle, Quick Attack, Growl, Tail Whip
    currentLevel: 5,
    catchRate: 40,
    experience: 0,
    evolvesTo: "RATICATE",
    evolutionLevel: 22,
  },
  RATICATE: {
    PokemonId: 61,
    name: "raticate",
    assetKey: POKEMON.RATICATE,
    assetFrame: 0,
    type: "NORMAL",
    baseAttack: 18,
    maxHp: 55,
    currentHp: 55,
    attackIds: [5, 11, 1, 3],
    currentLevel: 22,
    catchRate: 127,
    experience: 0,
    evolvesTo: "RATICATE",
    evolutionLevel: 100000,
  },
  MEOWTH: {
    PokemonId: 40,
    name: "meowth",
    assetKey: POKEMON.MEOWTH,
    assetFrame: 0,
    type: "NORMAL",
    baseAttack: 12,
    maxHp: 40,
    currentHp: 40,
    attackIds: [1, 3, 5, 8], // Growl, Tail Whip, Tackle, Water Gun
    currentLevel: 5,
    catchRate: 255,
    experience: 0,
    evolvesTo: "PERSIAN",
    evolutionLevel: 28,
  },
  PERSIAN: {
    PokemonId: 41,
    name: "persian",
    assetKey: POKEMON.PERSIAN,
    assetFrame: 0,
    type: "NORMAL",
    baseAttack: 20,
    maxHp: 65,
    currentHp: 65,
    attackIds: [1, 3, 5, 8],
    currentLevel: 28,
    catchRate: 90,
    experience: 0,
    evolvesTo: "PERSIAN",
    evolutionLevel: 100000,
  },

  // Ground Type Pokemon
  SANDSHREW: {
    PokemonId: 1,
    name: "sandshrew",
    assetKey: POKEMON.SANDSHREW,
    assetFrame: 0,
    type: "GROUND",
    baseAttack: 15,
    maxHp: 50,
    currentHp: 50,
    attackIds: [5, 7, 14, 11], // Tackle, Sand Attack, Mud Shot, Quick Attack
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "SANDSLASH",
    evolutionLevel: 22,
  },
  SANDSLASH: {
    PokemonId: 25,
    name: "sandslash",
    assetKey: POKEMON.SANDSLASH,
    assetFrame: 0,
    type: "GROUND",
    baseAttack: 20,
    maxHp: 75,
    currentHp: 75,
    attackIds: [5, 7, 14, 11],
    currentLevel: 22,
    catchRate: 45,
    experience: 0,
    evolvesTo: "SANDSLASH",
    evolutionLevel: 100000,
  },
  CUBONE: {
    PokemonId: 4,
    name: "cubone",
    assetKey: POKEMON.CUBONE,
    assetFrame: 0,
    type: "GROUND",
    baseAttack: 14,
    maxHp: 50,
    currentHp: 50,
    attackIds: [5, 7, 14, 3], // Tackle, Sand Attack, Mud Shot, Tail Whip
    currentLevel: 5,
    catchRate: 35,
    experience: 0,
    evolvesTo: "MAROWAK",
    evolutionLevel: 28,
  },
  MAROWAK: {
    PokemonId: 28,
    name: "marowak",
    assetKey: POKEMON.MAROWAK,
    assetFrame: 0,
    type: "GROUND",
    baseAttack: 18,
    maxHp: 60,
    currentHp: 60,
    attackIds: [5, 7, 14, 3],
    currentLevel: 28,
    catchRate: 35,
    experience: 0,
    evolvesTo: "MAROWAK",
    evolutionLevel: 100000,
  },

  // Rock Type Pokemon
  GEODUDE: {
    PokemonId: 3,
    name: "geodude",
    assetKey: POKEMON.GEODUDE,
    assetFrame: 0,
    type: "ROCK",
    baseAttack: 16,
    maxHp: 40,
    currentHp: 40,
    attackIds: [10, 17, 5, 1], // Rock Throw, Rock Slide, Tackle, Growl
    currentLevel: 5,
    catchRate: 40,
    experience: 0,
    evolvesTo: "GRAVELER",
    evolutionLevel: 25,
  },
  GRAVELER: {
    PokemonId: 26,
    name: "graveler",
    assetKey: POKEMON.GRAVELER,
    assetFrame: 0,
    type: "ROCK",
    baseAttack: 22,
    maxHp: 60,
    currentHp: 60,
    attackIds: [10, 17, 5, 1],
    currentLevel: 25,
    catchRate: 40,
    experience: 0,
    evolvesTo: "GOLEM",
    evolutionLevel: 1000, // Trade evolution
  },
  GOLEM: {
    PokemonId: 27,
    name: "golem",
    assetKey: POKEMON.GOLEM,
    assetFrame: 0,
    type: "ROCK",
    baseAttack: 28,
    maxHp: 80,
    currentHp: 80,
    attackIds: [10, 17, 5, 1],
    currentLevel: 30,
    catchRate: 30,
    experience: 0,
    evolvesTo: "GOLEM",
    evolutionLevel: 100000,
  },

  // Water Type Pokemon
  SQUIRTLE: {
    PokemonId: 6,
    name: "squirtle",
    assetKey: POKEMON.SQUIRTLE,
    assetFrame: 0,
    type: "WATER",
    baseAttack: 13,
    maxHp: 44,
    currentHp: 44,
    attackIds: [8, 15, 5, 11], // Water Gun, Bubble, Tackle, Quick Attack
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "WARTORTLE",
    evolutionLevel: 16,
  },
  WARTORTLE: {
    PokemonId: 29,
    name: "wartortle",
    assetKey: POKEMON.WARTORTLE,
    assetFrame: 0,
    type: "WATER",
    baseAttack: 18,
    maxHp: 59,
    currentHp: 59,
    attackIds: [8, 15, 5, 11],
    currentLevel: 16,
    catchRate: 45,
    experience: 0,
    evolvesTo: "BLASTOISE",
    evolutionLevel: 36,
  },
  BLASTOISE: {
    PokemonId: 30,
    name: "blastoise",
    assetKey: POKEMON.BLASTOISE,
    assetFrame: 0,
    type: "WATER",
    baseAttack: 25,
    maxHp: 79,
    currentHp: 79,
    attackIds: [8, 15, 5, 11],
    currentLevel: 36,
    catchRate: 45,
    experience: 0,
    evolvesTo: "BLASTOISE",
    evolutionLevel: 100000,
  },
  PSYDUCK: {
    PokemonId: 59,
    name: "psyduck",
    assetKey: POKEMON.PSYDUCK,
    assetFrame: 0,
    type: "WATER",
    baseAttack: 14,
    maxHp: 50,
    currentHp: 50,
    attackIds: [8, 15, 19, 20], // Water Gun, Bubble, Confusion, Hydro Pump
    currentLevel: 5,
    catchRate: 190,
    experience: 0,
    evolvesTo: "GOLDUCK",
    evolutionLevel: 33,
  },
  GOLDUCK: {
    PokemonId: 60,
    name: "golduck",
    assetKey: POKEMON.GOLDUCK,
    assetFrame: 0,
    type: "WATER",
    baseAttack: 22,
    maxHp: 80,
    currentHp: 80,
    attackIds: [8, 15, 19, 20],
    currentLevel: 33,
    catchRate: 75,
    experience: 0,
    evolvesTo: "GOLDUCK",
    evolutionLevel: 100000,
  },

  // Fire Type Pokemon
  CHARMANDER: {
    PokemonId: 9,
    name: "charmander",
    assetKey: POKEMON.CHARMANDER,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 14,
    maxHp: 39,
    currentHp: 39,
    attackIds: [9, 16, 5, 11], // Ember, Fire Spin, Tackle, Quick Attack
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "CHARMELEON",
    evolutionLevel: 16,
  },
  CHARMELEON: {
    PokemonId: 31,
    name: "charmeleon",
    assetKey: POKEMON.CHARMELEON,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 18,
    maxHp: 58,
    currentHp: 58,
    attackIds: [9, 16, 5, 11],
    currentLevel: 16,
    catchRate: 45,
    experience: 0,
    evolvesTo: "CHARIZARD",
    evolutionLevel: 36,
  },
  CHARIZARD: {
    PokemonId: 32,
    name: "charizard",
    assetKey: POKEMON.CHARIZARD,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 25,
    maxHp: 78,
    currentHp: 78,
    attackIds: [9, 16, 5, 11],
    currentLevel: 36,
    catchRate: 45,
    experience: 0,
    evolvesTo: "CHARIZARD",
    evolutionLevel: 100000,
  },
  VULPIX: {
    PokemonId: 45,
    name: "vulpix",
    assetKey: POKEMON.VULPIX,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 15,
    maxHp: 38,
    currentHp: 38,
    attackIds: [9, 16, 5, 10], // Ember, Fire Spin, Tackle, Rock Throw
    currentLevel: 5,
    catchRate: 190,
    experience: 0,
    evolvesTo: "NINETALES",
    evolutionLevel: 100000, // Fire Stone evolution
  },
  NINETALES: {
    PokemonId: 46,
    name: "ninetales",
    assetKey: POKEMON.NINETALES,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 24,
    maxHp: 73,
    currentHp: 73,
    attackIds: [9, 16, 5, 10],
    currentLevel: 16,
    catchRate: 75,
    experience: 0,
    evolvesTo: "NINETALES",
    evolutionLevel: 100000,
  },
  GROWLITHE: {
    PokemonId: 50,
    name: "growlithe",
    assetKey: POKEMON.GROWLITHE,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 15,
    maxHp: 55,
    currentHp: 55,
    attackIds: [9, 16, 5, 11], // Ember, Fire Spin, Tackle, Quick Attack
    currentLevel: 5,
    catchRate: 190,
    experience: 0,
    evolvesTo: "ARCANINE",
    evolutionLevel: 100000, // Fire Stone evolution
  },
  ARCANINE: {
    PokemonId: 51,
    name: "arcanine",
    assetKey: POKEMON.ARCANINE,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 25,
    maxHp: 90,
    currentHp: 90,
    attackIds: [9, 16, 5, 11],
    currentLevel: 20,
    catchRate: 75,
    experience: 0,
    evolvesTo: "ARCANINE",
    evolutionLevel: 100000,
  },

  // Grass Type Pokemon
  BULBASAUR: {
    PokemonId: 33,
    name: "bulbasaur",
    assetKey: POKEMON.BULBASAUR,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 14,
    maxHp: 45,
    currentHp: 45,
    attackIds: [4, 12, 5, 8], // Thunder Wave, Thunderbolt, Tackle, Water Gun
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "IVYSAUR",
    evolutionLevel: 16,
  },
  IVYSAUR: {
    PokemonId: 34,
    name: "ivysaur",
    assetKey: POKEMON.IVYSAUR,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 18,
    maxHp: 60,
    currentHp: 60,
    attackIds: [4, 12, 5, 8],
    currentLevel: 16,
    catchRate: 45,
    experience: 0,
    evolvesTo: "VENUSAUR",
    evolutionLevel: 32,
  },
  VENUSAUR: {
    PokemonId: 35,
    name: "venusaur",
    assetKey: POKEMON.VENUSAUR,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 25,
    maxHp: 80,
    currentHp: 80,
    attackIds: [4, 12, 5, 8],
    currentLevel: 32,
    catchRate: 45,
    experience: 0,
    evolvesTo: "VENUSAUR",
    evolutionLevel: 100000,
  },
  CHIKORITA: {
    PokemonId: 47,
    name: "chikorita",
    assetKey: POKEMON.CHIKORITA,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 14,
    maxHp: 45,
    currentHp: 45,
    attackIds: [4, 6, 5, 13], // Thunder Wave, Vine Whip, Tackle, Razor Leaf
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "BAYLEEF",
    evolutionLevel: 16,
  },
  BAYLEEF: {
    PokemonId: 48,
    name: "bayleef",
    assetKey: POKEMON.BAYLEEF,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 18,
    maxHp: 60,
    currentHp: 60,
    attackIds: [4, 6, 5, 13],
    currentLevel: 16,
    catchRate: 45,
    experience: 0,
    evolvesTo: "MEGANIUM",
    evolutionLevel: 32,
  },
  MEGANIUM: {
    PokemonId: 49,
    name: "meganium",
    assetKey: POKEMON.MEGANIUM,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 24,
    maxHp: 80,
    currentHp: 80,
    attackIds: [4, 6, 5, 13],
    currentLevel: 32,
    catchRate: 45,
    experience: 0,
    evolvesTo: "MEGANIUM",
    evolutionLevel: 100000,
  },
  ODDISH: {
    PokemonId: 55,
    name: "oddish",
    assetKey: POKEMON.ODDISH,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 13,
    maxHp: 45,
    currentHp: 45,
    attackIds: [4, 6, 13, 18], // Thunder Wave, Vine Whip, Razor Leaf, Petal Dance
    currentLevel: 5,
    catchRate: 255,
    experience: 0,
    evolvesTo: "GLOOM",
    evolutionLevel: 21,
  },
  GLOOM: {
    PokemonId: 56,
    name: "gloom",
    assetKey: POKEMON.GLOOM,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 17,
    maxHp: 60,
    currentHp: 60,
    attackIds: [4, 6, 13, 18],
    currentLevel: 21,
    catchRate: 120,
    experience: 0,
    evolvesTo: "VILEPLUME",
    evolutionLevel: 100000, // Leaf Stone evolution
  },
  VILEPLUME: {
    PokemonId: 57,
    name: "vileplume",
    assetKey: POKEMON.VILEPLUME,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 23,
    maxHp: 75,
    currentHp: 75,
    attackIds: [4, 6, 13, 18],
    currentLevel: 25,
    catchRate: 45,
    experience: 0,
    evolvesTo: "VILEPLUME",
    evolutionLevel: 100000,
  },
  BELLOSSOM: {
    PokemonId: 58,
    name: "bellossom",
    assetKey: POKEMON.BELLOSSOM,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 20,
    maxHp: 75,
    currentHp: 75,
    attackIds: [4, 6, 13, 18],
    currentLevel: 25,
    catchRate: 45,
    experience: 0,
    evolvesTo: "BELLOSSOM",
    evolutionLevel: 100000,
  },

  // Electric Type Pokemon
  PIKACHU: {
    PokemonId: 36,
    name: "pikachu",
    assetKey: POKEMON.PIKACHU,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 15,
    maxHp: 35,
    currentHp: 35,
    attackIds: [13, 15, 5, 11], // Razor Leaf, Bubble, Tackle, Quick Attack
    currentLevel: 5,
    catchRate: 190,
    experience: 0,
    evolvesTo: "RAICHU",
    evolutionLevel: 20, // Thunder Stone evolution
  },
  RAICHU: {
    PokemonId: 37,
    name: "raichu",
    assetKey: POKEMON.RAICHU,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 20,
    maxHp: 60,
    currentHp: 60,
    attackIds: [13, 15, 5, 11],
    currentLevel: 16,
    catchRate: 75,
    experience: 0,
    evolvesTo: "RAICHU",
    evolutionLevel: 100000,
  },
  ELECTRIKE: {
    PokemonId: 38,
    name: "electrike",
    assetKey: POKEMON.ELECTRIKE,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 17,
    maxHp: 40,
    currentHp: 40,
    attackIds: [13, 15, 5, 11], // Razor Leaf, Bubble, Tackle, Quick Attack
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "MANECTRIC",
    evolutionLevel: 26,
  },
  MANECTRIC: {
    PokemonId: 39,
    name: "manectric",
    assetKey: POKEMON.MANECTRIC,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 25,
    maxHp: 70,
    currentHp: 70,
    attackIds: [13, 15, 5, 11],
    currentLevel: 26,
    catchRate: 45,
    experience: 0,
    evolvesTo: "MANECTRIC",
    evolutionLevel: 100000,
  },
  MAGNEMITE: {
    PokemonId: 52,
    name: "magnemite",
    assetKey: POKEMON.MAGNEMITE,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 14,
    maxHp: 25,
    currentHp: 25,
    attackIds: [2, 4, 5, 12], // Thunder Shock, Thunder Wave, Tackle, Thunderbolt
    currentLevel: 5,
    catchRate: 190,
    experience: 0,
    evolvesTo: "MAGNETON",
    evolutionLevel: 30,
  },
  MAGNETON: {
    PokemonId: 53,
    name: "magneton",
    assetKey: POKEMON.MAGNETON,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 22,
    maxHp: 50,
    currentHp: 50,
    attackIds: [2, 4, 5, 12],
    currentLevel: 30,
    catchRate: 120,
    experience: 0,
    evolvesTo: "MAGNEZONE",
    evolutionLevel: 100000, // Special magnetic field evolution
  },
  MAGNEZONE: {
    PokemonId: 54,
    name: "magnezone",
    assetKey: POKEMON.MAGNEZONE,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 28,
    maxHp: 70,
    currentHp: 70,
    attackIds: [2, 4, 5, 12],
    currentLevel: 35,
    catchRate: 60,
    experience: 0,
    evolvesTo: "MAGNEZONE",
    evolutionLevel: 100000,
  },

  // Flying Type Pokemon
  PIDGEY: {
    PokemonId: 42,
    name: "pidgey",
    assetKey: POKEMON.PIDGEY,
    assetFrame: 0,
    type: "FLYING",
    baseAttack: 12,
    maxHp: 40,
    currentHp: 40,
    attackIds: [2, 6, 5, 9], // Thunder Shock, Vine Whip, Tackle, Ember
    currentLevel: 5,
    catchRate: 255,
    experience: 0,
    evolvesTo: "PIDGEOTTO",
    evolutionLevel: 18,
  },
  PIDGEOTTO: {
    PokemonId: 43,
    name: "pidgeotto",
    assetKey: POKEMON.PIDGEOTTO,
    assetFrame: 0,
    type: "FLYING",
    baseAttack: 20,
    maxHp: 63,
    currentHp: 63,
    attackIds: [2, 6, 5, 9],
    currentLevel: 18,
    catchRate: 120,
    experience: 0,
    evolvesTo: "PIDGEOT",
    evolutionLevel: 36,
  },
  PIDGEOT: {
    PokemonId: 44,
    name: "pidgeot",
    assetKey: POKEMON.PIDGEOT,
    assetFrame: 0,
    type: "FLYING",
    baseAttack: 25,
    maxHp: 83,
    currentHp: 83,
    attackIds: [2, 6, 5, 9],
    currentLevel: 36,
    catchRate: 45,
    experience: 0,
    evolvesTo: "PIDGEOT",
    evolutionLevel: 100000,
  }
};
